trigger:
  - main

pr:
  - main

variables:
- template: eng/common-variables.yml

stages:
- stage: build
  displayName: Build
  jobs:
  - template: /eng/common/templates/jobs/jobs.yml
    parameters:
      workspace:
        clean: all
      jobs:
      - job: Windows
        timeoutInMinutes: 90
        pool:
          name: NetCore-Public
          demands: ImageOverride -equals Windows.vs2022.amd64.open

        preSteps:
        - checkout: self
          clean: true
        steps:
        - script: Build.cmd -test
          displayName: Run Tests

  - job: Linux
    timeoutInMinutes: 30
    pool:
      name: NetCore-Public
      demands: ImageOverride -equals build.ubuntu.2204.amd64.open
    steps:
    - checkout: self
      displayName: Checkout Self
      clean: true
    - script: ./build.sh --test
      displayName: Run Tests

  - job: MacOS
    timeoutInMinutes: 45
    pool: 
      vmImage: 'macOS-latest'
    steps:
    - checkout: self
      displayName: Checkout Self
      clean: true
    - script: ./build.sh --test
      displayName: Run Tests
