trigger:
  - main

pr:
  - main

variables:
- template: eng/common-variables.yml

stages:
- stage: build
  displayName: Build
  jobs:
  - template: /eng/common/templates/jobs/jobs.yml
    parameters:
      workspace:
        clean: all
      jobs:
      - job: Windows
        displayName: Tests (Helix)
        timeoutInMinutes: 60
        pool:
          name: NetCore-Public
          demands: ImageOverride -equals Windows.vs2022.amd64.open

        variables:
          _BuildConfig: Debug

        preSteps:
        - checkout: self
          clean: true
        steps:
        - task: UseDotNet@2
          displayName: Get .NET Core SDK
          inputs:
            version: 8.x
        - powershell: |
            $dest = "$(Build.StagingDirectory)\helix-payload\src"
            New-Item -ItemType Directory -Path $dest -Force | Out-Null
            Copy-Item -Path "$(Build.SourcesDirectory)\src\*" -Destination $dest -Recurse
          displayName: Prepare Helix Correlation Payload
        - template: /eng/common/templates/steps/send-to-helix.yml
          parameters:
            HelixSource: pr/dotnet/install-scripts/$(Build.SourceBranch)
            HelixTargetQueues: Windows.10.Amd64.Open;Ubuntu.2204.Amd64.Open;OSX.15.ARM64.Open
            XUnitProjects: $(Build.SourcesDirectory)\tests\Install-Scripts.Test\Install-Scripts.Test.csproj
            XUnitPublishTargetFramework: net8.0
            XUnitRuntimeTargetFramework: netcoreapp2.0
            XUnitRunnerVersion: 2.4.2
            IncludeDotNetCli: true
            DotNetCliPackageType: sdk
            DotNetCliVersion: 8.0.126
            CorrelationPayloadDirectory: $(Build.StagingDirectory)\helix-payload
            Creator: install-scripts
